In [5]:
import pandas as pd

In [ ]:
# df = pd.read_csv("../Data/Teen_Mental_Health_Dataset.csv")
df = pd.read_csv("../Data/job_salary_prediction_dataset.csv")

df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [8]:
df.shape

(250000, 10)

In [9]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [10]:
df['job_title'].value_counts()

job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64

In [11]:
# df.loc[(df['age'] == 19 ) & (df['academic_year'] == 2)]
# df.loc[(df['age'] == 19 ) & (df['platform_usage'] == 'TikTok')]
df.loc[(df['job_title'] == 'Data Analyst' ) & (df['industry'] == 'Media')]

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
60,Data Analyst,2,Master,6,Media,Startup,Australia,Hybrid,1,89018
246,Data Analyst,9,Bachelor,17,Media,Small,UK,Hybrid,4,113902
515,Data Analyst,1,Bachelor,2,Media,Startup,Singapore,Hybrid,5,76120
1010,Data Analyst,11,Bachelor,9,Media,Small,Canada,No,3,129724
1062,Data Analyst,1,Master,6,Media,Large,Canada,Hybrid,2,120140
...,...,...,...,...,...,...,...,...,...,...
248827,Data Analyst,20,Bachelor,1,Media,Small,Netherlands,No,2,120035
249018,Data Analyst,15,PhD,13,Media,Enterprise,Sweden,Yes,2,167080
249092,Data Analyst,9,PhD,6,Media,Enterprise,Singapore,No,4,142961
249693,Data Analyst,12,Master,17,Media,Small,Germany,Yes,4,149795
249915,Data Analyst,10,Diploma,5,Media,Enterprise,Remote,Hybrid,2,114769

In [12]:
df.iloc[0:8, 0:3]

                   job_title  experience_years education_level
0                AI Engineer                10        Bachelor
1               Data Analyst                 5        Bachelor
2         Frontend Developer                18             PhD
3           Business Analyst                19             PhD
4            Product Manager                15        Bachelor
5                AI Engineer                 0     High School
6          Backend Developer                 6     High School
7  Machine Learning Engineer                 4        Bachelor

In [13]:
# df.sort_values(by='academic_yeat', ascendng=False)
# df.sort_values(by='platform_usage', ascending=False)
df.sort_values(by='job_title', ascending=False)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
121749,Software Engineer,17,PhD,10,Finance,Large,India,No,0,117064
37884,Software Engineer,15,PhD,11,Manufacturing,Medium,Australia,Hybrid,0,150256
76160,Software Engineer,1,Master,14,Consulting,Enterprise,UK,Yes,4,169105
17959,Software Engineer,15,High School,18,Retail,Medium,Canada,Yes,0,168534
160371,Software Engineer,4,Bachelor,4,Retail,Enterprise,Sweden,No,2,134347
...,...,...,...,...,...,...,...,...,...,...
199780,AI Engineer,12,Master,4,Education,Large,Sweden,Hybrid,1,180598
199777,AI Engineer,11,Diploma,14,Healthcare,Large,USA,No,5,235794
199775,AI Engineer,17,Master,14,Technology,Small,Australia,Yes,2,175552
199769,AI Engineer,1,Master,8,Retail,Enterprise,Singapore,Yes,3,182950
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413

In [14]:
# Rename or drop columns

In [15]:
# Check and fix data types if necessary

In [16]:
# use .isna() / .isnull() to identify missing values
df.isna().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [17]:
# use .duplicated() ti check for duplicate rows and .drop_duplicates() if needed
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
249995    False
249996    False
249997    False
249998    False
249999    False
Length: 250000, dtype: bool